site_name: CAM Slicer Docs
repo_url: https://github.com/example/cam_slicer
docs_dir: docs
site_dir: site
nav:
  - Home: index.md
  - API Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys, os; sys.path.insert(0, os.path.abspath('.'))
