@@ -56,50 +56,51 @@
 from .importers import (
     analyze_stl,
     mesh_simplify,
     import_and_vectorize_image,
     import_svg,
 )
 from .core.mesh_strategies import (
     generate_roughing_paths,
     generate_finishing_paths,
     generate_carving_paths,
     generate_zlevel_roughing_paths,
     generate_zlevel_finishing_paths,
     generate_parallel_finishing_paths,
     generate_offset_finishing_paths,
     generate_high_polish_paths,
     generate_radial_finishing_paths,
     project_curves_to_surface,
     plan_mesh_operations,
 )
 from .cli_wizard import cli
 
 try:  # optional dependency
     from .api_server import create_app
 except Exception:  # pragma: no cover - missing FastAPI
     create_app = None
 from .sensors import generate_heightmap, export_heightmap_to_json
+from .probing import probe_heightmap
 from .sender import (
     stream_gcode_live,
     stream_gcode_to_grbl,
     LiveGcodeStreamer,
     stream_gcode_with_feedback,
     stream_with_recovery,
     resume_job,
     save_checkpoint,
     load_checkpoint,
 )
@@ -223,50 +224,51 @@
     "axis_limits",
     "GeoFence",
     "get_active_geofence",
     "reset_active_geofence",
     "assign_hybrid_operations",
     "blend_additive_subtractive",
     "blend_laser_mill",
     "schedule_multi_head_job",
     "prepare_hybrid_job",
     "clip_toolpath_to_regions",
     "Strategy",
     "load_strategy",
     "run_strategy",
     "run_macro_sequence",
     "batch_process_toolpaths",
     "generate_adaptive_path",
     "compute_adaptive_steps",
     "generate_spiral_helix",
     "morph_between_curves",
     "get_macro",
     "get_machine_config",
     "ToolDatabase",
     "ToolMaterialDB",
     "generate_heightmap",
     "export_heightmap_to_json",
+    "probe_heightmap",
     "stream_gcode_live",
     "stream_gcode_to_grbl",
     "LiveGcodeStreamer",
     "stream_gcode_with_feedback",
     "stream_with_recovery",
     "resume_job",
     "save_checkpoint",
     "load_checkpoint",
     "optimize_toolpath_based_on_surface",
     "optimize_toolpath",
     "optimize_toolpath_sequence",
     "optimize_toolpath_sequence_tsp",
     "smooth_toolpath_corners",
     "filter_small_arcs",
     "optimize_high_speed_toolpath",
     "detect_debris",
     "add_debris_zones_from_image",
     "plan_toolpath_avoiding_debris",
     "AIFeedbackAdvisor",
     "ToolpathPredictor",
     "MaterialSimulator",
     "ForcePredictor",
     "simulate_force_profile",
     "ChipCoolantAdvisor",
     "apply_chip_evacuations",
